sudo: no
language: python
install:
  - pip install tox coveralls
script:
  - tox
env:
  - PIP_DOWNLOAD_CACHE=pip_cache py26-django14
  - PIP_DOWNLOAD_CACHE=pip_cache py27-django14
  - PIP_DOWNLOAD_CACHE=pip_cache py26-django15
  - PIP_DOWNLOAD_CACHE=pip_cache py27-django15
  - PIP_DOWNLOAD_CACHE=pip_cache py-27-django16
  - PIP_DOWNLOAD_CACHE=pip_cache py-27-django17
  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=coverage
  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=flake8
after_success: coveralls
cache:
  directories:
    - pip_cache
branches:
  only:
    - develop
