sudo: no
language: python
install:
  - pip install tox coveralls
script:
  - tox
env:
  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=django14
  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=django15
  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=django16
  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=django17
  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=coverage
  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=flake8
after_success: coveralls
cache:
  directories:
    - pip_cache
branches:
  only:
    - develop
